# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Activity Campaign
email: nukeador@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
    Mozilla Activity Campaign
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nukeador.github.io/activity-campaign" # the base hostname & protocol for your site
github.url: "https://nukeador.github.io/activity-campaign" # Github url
twitter_username: mozparticipate
github_username:  mozilla

# Build settings
markdown: kramdown

include: ['_pages']
